## Preprocessing

In [32]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [33]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=["EIN", "NAME"])

In [34]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [35]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
counts = application_df['APPLICATION_TYPE'].value_counts()
counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [36]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff = 500
application_types_to_replace = list(counts[counts < cutoff].index)
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [37]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification = application_df['CLASSIFICATION'].value_counts()
classification

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [38]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classifications_one = classification.loc[classification > 1]
classifications_one

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [39]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
class_cutoff = 1000
class_type = application_df['CLASSIFICATION'].value_counts()
classifications_to_replace = list(classification[classification < class_cutoff].index)
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [40]:
# Convert categorical data to numeric with `pd.get_dummies`
dummy = pd.get_dummies(application_df, dtype=int)
dummy.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [41]:
# Split our preprocessed data into our features and target arrays
X = dummy.drop("IS_SUCCESSFUL", axis=1).values
y = dummy["IS_SUCCESSFUL"].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 10)

In [42]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [51]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp): # needs to be hp
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh'])

    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=10,
        step=2), activation=activation, input_dim=43))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 6)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=10,
            step=2),
            activation=activation))

    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])

    return nn_model

In [52]:
# Import the kerastuner library

import keras_tuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=20,
    hyperband_iterations=2)

Reloading Tuner from ./untitled_project/tuner0.json

In [53]:
tuner.search(X_train_scaled, y_train, epochs=50, validation_split=0.2)

Trial 56 Complete [00h 00m 55s]
val_accuracy: 0.5360544323921204

Best val_accuracy So Far: 0.7267249822616577
Total elapsed time: 02h 16m 28s

In [54]:
# Train the model

best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]

# Build the model with the best hyperparameters and train it
model = create_model(best_hps)
fit_model = model.fit(X_train_scaled, y_train, epochs=80)

Epoch 1/80
804/804 [==============================] - 4s 3ms/step - loss: 0.6338 - accuracy: 0.6618
Epoch 2/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5787 - accuracy: 0.7199
Epoch 3/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5758 - accuracy: 0.7227
Epoch 4/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5739 - accuracy: 0.7241
Epoch 5/80
804/804 [==============================] - 3s 3ms/step - loss: 0.5721 - accuracy: 0.7237
Epoch 6/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5712 - accuracy: 0.7250
Epoch 7/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5702 - accuracy: 0.7248
Epoch 8/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5701 - accuracy: 0.7251
Epoch 9/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5696 - accuracy: 0.7245
Epoch 10/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5693 - accuracy: 0.7256
Epoch 11/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5690 - accuracy: 0.7250
Epoch 12/80
804/804 [==============================] - 3s 3ms/step - loss: 0.5691 - accuracy: 0.7246
Epoch 13/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5690 - accuracy: 0.7249
Epoch 14/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5687 - accuracy: 0.7253
Epoch 15/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5685 - accuracy: 0.7251
Epoch 16/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5684 - accuracy: 0.7252
Epoch 17/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5685 - accuracy: 0.7255
Epoch 18/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5677 - accuracy: 0.7255
Epoch 19/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5679 - accuracy: 0.7260
Epoch 20/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5677 - accuracy: 0.7264
Epoch 21/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5677 - accuracy: 0.7262
Epoch 22/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5676 - accuracy: 0.7266
Epoch 23/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5675 - accuracy: 0.7267
Epoch 24/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5674 - accuracy: 0.7264
Epoch 25/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5674 - accuracy: 0.7263
Epoch 26/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5670 - accuracy: 0.7268
Epoch 27/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5672 - accuracy: 0.7268
Epoch 28/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5672 - accuracy: 0.7266
Epoch 29/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5671 - accuracy: 0.7263
Epoch 30/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5668 - accuracy: 0.7265
Epoch 31/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5669 - accuracy: 0.7264
Epoch 32/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5670 - accuracy: 0.7258
Epoch 33/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5670 - accuracy: 0.7260
Epoch 34/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5667 - accuracy: 0.7268
Epoch 35/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5666 - accuracy: 0.7263
Epoch 36/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5668 - accuracy: 0.7266
Epoch 37/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5670 - accuracy: 0.7261
Epoch 38/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5669 - accuracy: 0.7264
Epoch 39/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5665 - accuracy: 0.7262
Epoch 40/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5665 - accuracy: 0.7261
Epoch 41/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5668 - accuracy: 0.7262
Epoch 42/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5665 - accuracy: 0.7263
Epoch 43/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5665 - accuracy: 0.7262
Epoch 44/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5664 - accuracy: 0.7254
Epoch 45/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5667 - accuracy: 0.7262
Epoch 46/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5663 - accuracy: 0.7263
Epoch 47/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5669 - accuracy: 0.7259
Epoch 48/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5664 - accuracy: 0.7269
Epoch 49/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5665 - accuracy: 0.7265
Epoch 50/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5665 - accuracy: 0.7258
Epoch 51/80
804/804 [==============================] - 3s 3ms/step - loss: 0.5663 - accuracy: 0.7259
Epoch 52/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5665 - accuracy: 0.7263
Epoch 53/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5664 - accuracy: 0.7268
Epoch 54/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5667 - accuracy: 0.7262
Epoch 55/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5664 - accuracy: 0.7259
Epoch 56/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5665 - accuracy: 0.7260
Epoch 57/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5664 - accuracy: 0.7267
Epoch 58/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5667 - accuracy: 0.7265
Epoch 59/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5663 - accuracy: 0.7263
Epoch 60/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5664 - accuracy: 0.7265
Epoch 61/80
804/804 [==============================] - 3s 3ms/step - loss: 0.5664 - accuracy: 0.7261
Epoch 62/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5665 - accuracy: 0.7261
Epoch 63/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5662 - accuracy: 0.7262
Epoch 64/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5665 - accuracy: 0.7260
Epoch 65/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5663 - accuracy: 0.7256
Epoch 66/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5663 - accuracy: 0.7252
Epoch 67/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5665 - accuracy: 0.7261
Epoch 68/80
804/804 [==============================] - 3s 3ms/step - loss: 0.5663 - accuracy: 0.7257
Epoch 69/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5663 - accuracy: 0.7261
Epoch 70/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5665 - accuracy: 0.7260
Epoch 71/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5661 - accuracy: 0.7263
Epoch 72/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5665 - accuracy: 0.7265
Epoch 73/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5663 - accuracy: 0.7262
Epoch 74/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5664 - accuracy: 0.7267
Epoch 75/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5663 - accuracy: 0.7260
Epoch 76/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5663 - accuracy: 0.7262
Epoch 77/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5664 - accuracy: 0.7262
Epoch 78/80
804/804 [==============================] - 3s 4ms/step - loss: 0.5663 - accuracy: 0.7250
Epoch 79/80
804/804 [==============================] - 3s 3ms/step - loss: 0.5663 - accuracy: 0.7261
Epoch 80/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5660 - accuracy: 0.7263

In [56]:
# Evaluate the model using the test data
model_loss, model_accuracy = model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5724 - accuracy: 0.7165 - 1s/epoch - 4ms/step
Loss: 0.5723530054092407, Accuracy: 0.7165014743804932

In [57]:
# Export our model to HDF5 file
model.save('h5Files/AlphabetSoupCharity2.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(